import type { Metadata } from "next";
import { Geist, Geist_Mono, Piedra } from "next/font/google";
import "./globals.css";
import SessionWrapper from "@/ui/provider";
import { UserProvider } from "@/context/UseSessionContext";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const piedra = Piedra({
  variable: "--font-piedra",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${piedra.variable}`}
      >
        <UserProvider>
          <SessionWrapper>{children}</SessionWrapper>
        </UserProvider>
      </body>
    </html>
  );
}
